import { Router } from 'express';
import multer from 'multer';
import { protect } from '../middleware/auth.js';
import { authorize } from '../middleware/roles.js';
import * as ctrl from '../controllers/emergency.controller.js';
const upload = multer({ dest: 'src/uploads/' });
const router = Router();
router.use(protect, authorize('EMERGENCY_OFFICER'));
router.get('/alerts', ctrl.listAlerts);
router.post('/alerts/ack/:id', ctrl.ackAlert);
router.post('/alerts/close/:id', ctrl.closeAlert);
router.post('/alerts/trigger', ctrl.triggerManualAlert);
router.post('/protocol/activate', ctrl.activateProtocol);
router.post('/messages', ctrl.sendMessage);
router.get('/messages', ctrl.getMessages);
router.post('/incidents', upload.array('attachments', 6), ctrl.createIncident);
router.put('/incidents/:id', ctrl.updateIncident);
router.get('/incidents', ctrl.listIncidents);
export default router;
